# -*- coding: utf-8 -*-
"""Analisis_Data_Laboratorio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dJs8990hvprmehXYPA1XWbf34wR3HjUp

# MÓDULO: ANÁLISIS EXPLORATORIO Y MACHINE LEARNING APLICADO
## TEMA: Análisis Metrológico y Modelado Predictivo de Calibraciones Industriales en el Ecuador
### Laboratorio de Calibración Acreditado bajo la Norma NTE INEN ISO/IEC 17025

**Estudiante:** [Tu Nombre Completo]  
**Docente:** [Nombre del Docente]  
**Fecha:** 12 de Julio de 2026  

---

## 1. Índice o Tabla de Contenido
1. [Carga de Librerías y Entorno](#seccion1)
2. [Carga y Lectura del Dataset](#seccion2)
3. [Descripción del Dataset y Contexto Metrológico](#seccion3)
4. [Limpieza y Preparación de Datos Robustecida](#seccion4)
5. [Análisis Exploratorio de Datos (EDA) Metrológico](#seccion5)
6. [Visualización Interactiva Avanzada (10 Gráficos)](#seccion6)
7. [Desarrollo del Modelo de Machine Learning Supervisado](#seccion7)
8. [Resultados, Interpretación Metrológica y Conclusiones](#seccion8)
"""

# ==============================================================================
# 1. CARGA DE LIBRERÍAS Y ENTORNO
# ==============================================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

# Librerías de Scikit-Learn para Preprocesamiento y Modelado
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Configuración estética por defecto para gráficos estáticos
sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

print("✅ Todas las librerías científicas han sido cargadas exitosamente.")

"""<a id="seccion2"></a>
## 2. Carga del Dataset
En esta sección cargaremos el archivo estructurado `calibraciones_laboratorio_ecuador.csv` provisto por el sistema nacional de servicios metrológicos. Utilizaremos el método nativo de *Pandas* para la lectura de datos e inspeccionaremos sus dimensiones y primeros registros.
"""

# ==============================================================================
# 2. CARGA Y LECTURA DEL DATASET
# ==============================================================================
# Leer el archivo CSV
df = pd.read_csv("/content/calibraciones_laboratorio_ecuador.csv")

# Evidenciando: shape, head() y unique()
print(f"📊 Dimensiones del Dataset original (shape): {df.shape}")
print("\n🔍 Primeros 3 registros (head):")
print(df.head(3).to_string())

print("\n🔢 Valores únicos en variable objetivo (unique):")
print(df['Estado_Final'].unique())

"""<a id="seccion3"></a>
## 3. Descripción del Dataset y Contexto Metrológico

### Contexto de la Fuente
El dataset registra los servicios de calibración en el territorio ecuatoriano bajo magnitudes críticas acreditadas ante el **SAE (Servicio de Acreditación Ecuatoriano)**: **Masa, Volumen, Temperatura y Presión**. Los datos vinculan las condiciones ambientales controladas del laboratorio o campo con variables logísticas (días desde la última calibración) y físicas (Error Encontrado e Incertidumbre).

A continuación ejecutamos un diagnóstico de los tipos de datos asignados por el intérprete para planificar las conversiones analíticas requeridas.
"""

# ==============================================================================
# 3. DIAGNÓSTICO E INFORMACIÓN ESTRUCTURAL (info)
# ==============================================================================
print("📋 Resumen estructural de tipos de datos de las columnas (info):")
df.info()

print("\n🔢 Valores únicos por columna categórica fundamental (unique):")
for col in ['Ciudad', 'Sector_Industrial', 'Magnitud', 'Estado_Final']:
    print(f" - {col}: {df[col].unique()}")

"""<a id="seccion4"></a>
## 4. Limpieza y Preparación de Datos Robustecida

Esta sección aborda tres desafíos críticos de calidad de datos introducidos de manera intencional:
1. **Heterogeneidad de formatos en fechas:** Existen formatos de tipo `YYYY-MM-DD`, `DD/MM/YYYY` y `YYYY.MM.DD`. Usaremos `pd.to_datetime` con parámetros de parseo mixtos y flexibles para homogeneizarlos.
2. **Valores Faltantes (NaN):** Las variables ambientales y de uso poseen valores nulos que requieren imputación basada en la física geográfica (ej. imputar la presión barométrica usando la mediana agrupada por la ciudad del cliente).
3. **Formatos Numéricos Ocultos:** Las columnas metrológicas `Error_Encontrado` e `Incertidumbre` se encuentran almacenadas como texto (`object`) debido al formateo estricto de cifras significativas. Deben ser casteadas a valores flotantes numéricos.
"""

# ==============================================================================
# 4. LIMPIEZA Y PREPARACIÓN DE DATOS
# ==============================================================================

# 4.1 Identificación inicial de nulos y duplicados
print("❌ Nulos iniciales por columna (isnull().sum()):")
print(df.isnull().sum())
print(f"\n🔄 Cantidad de filas duplicadas antes de limpiar: {df.duplicated().sum()}")

# Eliminar duplicados si existieran
df = df.drop_duplicates()

# 4.2 Conversión obligatoria de tipos de datos numéricos (astype)
df['Error_Encontrado'] = df['Error_Encontrado'].astype(float)
df['Incertidumbre'] = df['Incertidumbre'].astype(float)

# 4.3 Tratamiento robusto de fechas mixtas
df['Fecha_Servicio'] = pd.to_datetime(df['Fecha_Servicio'], errors='coerce', format='mixed')

# 4.4 Imputación Metrológica/Geográfica de Valores Nulos
# La presión barométrica depende estrictamente de la altitud de la ciudad (Quito vs Guayaquil)
df['Presion_Barometrica_hPa'] = df.groupby('Ciudad')['Presion_Barometrica_hPa'].transform(lambda x: x.fillna(x.median()))
df['Temp_Ambiente_C'] = df.groupby('Ciudad')['Temp_Ambiente_C'].transform(lambda x: x.fillna(x.median()))
df['Humedad_Relativa_perc'] = df.groupby('Ciudad')['Humedad_Relativa_perc'].transform(lambda x: x.fillna(x.median()))

# Evidenciando: astype()
# Convertimos las columnas metrológicas que venían formateadas como texto a flotantes numéricos
df['Error_Encontrado'] = df['Error_Encontrado'].astype(float)
df['Incertidumbre'] = df['Incertidumbre'].astype(float)

# Evidenciando: pd.to_datetime() con parámetros de parseo flexibles
df['Fecha_Servicio'] = pd.to_datetime(df['Fecha_Servicio'], errors='coerce', format='mixed')

# Imputar la antigüedad de uso con la mediana global
df['Dias_Desde_Ultima_Calibracion'] = df['Dias_Desde_Ultima_Calibracion'].fillna(df['Dias_Desde_Ultima_Calibracion'].median())

# Verificar que ya no existan valores nulos
print("\n🛡️ Nulos remanentes tras la limpieza y normalización:")
print(df.isnull().sum())

"""<a id="seccion5"></a>
## 5. Análisis Exploratorio de Datos (EDA) Metrológico

### Análisis Físico de Variables Críticas por Ciudad
Ecuador presenta microclimas drásticos debido a la Cordillera de los Andes. Ciudades de la Sierra como **Quito y Cuenca** se caracterizan por una presión atmosférica baja (aprox. 730 a 750 hPa) y humedades relativas controladas. Por el contrario, las terminales de la Costa como **Guayaquil y Manta** operan a nivel del mar con presiones estándar de la atmósfera física (~1012 hPa) y humedades ambientales severas que superan con facilidad el 75%.

A continuación empleamos `describe()`, `groupby()`, `agg()`, `pd.crosstab()` y `pivot_table()` para mapear esta realidad industrial.
"""

# ==============================================================================
# 5. MÉTODOS AVANZADOS DE DATAFRAME (EDA NUMÉRICO Y CATEGÓRICO)
# ==============================================================================

print("📈 Estadísticas Descriptivas Globales de Variables Metrológicas:")
print(df[['Temp_Ambiente_C', 'Humedad_Relativa_perc', 'Presion_Barometrica_hPa', 'Error_Encontrado', 'Dias_Desde_Ultima_Calibracion']].describe())

# Evidenciando: groupby() + agg()
print("\n🏢 Perfil Climático Promedio por Ciudad en Ecuador (groupby + agg):")
perfil_ciudad = df.groupby('Ciudad').agg({
    'Temp_Ambiente_C': 'mean',
    'Humedad_Relativa_perc': 'mean',
    'Presion_Barometrica_hPa': 'mean',
    'ID_Equipo': 'count'
}).rename(columns={'ID_Equipo': 'Total_Servicios'})
print(perfil_ciudad)

print("\n📊 Tabla de Contingencia Cruzada: Estado Final por Sector Industrial (pd.crosstab):")
print(pd.crosstab(df['Sector_Industrial'], df['Estado_Final'], margins=True))

print("\n🧪 Matriz de Pivote: Error Medio Encontrado por Magnitud y Ciudad (pivot_table):")
pivot_errores = df.pivot_table(values='Error_Encontrado', index='Magnitud', columns='Ciudad', aggfunc='mean')
print(pivot_errores)

print("\n📉 Matriz de Correlación Lineal (corr):")
print(df[['Temp_Ambiente_C', 'Humedad_Relativa_perc', 'Presion_Barometrica_hPa', 'Error_Encontrado', 'Dias_Desde_Ultima_Calibracion']].corr())

# Evidenciando: describe()
print("\n📈 Estadísticas Descriptivas del Dataset Limpio (describe):")
print(df.describe())

# Evidenciando: value_counts()
print("\n📊 Frecuencia de servicios por magnitud (value_counts):")
print(df['Magnitud'].value_counts())

# Evidenciando: sort_values()
print("\n⏳ Top 3 registros con mayor descalibración temporal (sort_values):")
print(df.sort_values(by='Dias_Desde_Ultima_Calibracion', ascending=False).head(3))

# Evidenciando: loc / iloc
print("\n🎯 Extracción específica metrológica mediante máscaras lógicas (loc):")
# Filtramos solo equipos de Masa en Guayaquil usando loc
print(df.loc[(df['Magnitud'] == 'Masa') & (df['Ciudad'] == 'Guayaquil'), ['ID_Equipo', 'Error_Encontrado']].head(2))

print("\n📍 Acceso posicional de control (iloc):")
# Primer registro, columnas esenciales posicionales
print(df.iloc[0, [0, 2, 4, 10, 12]])

# Evidenciando: pd.crosstab()
print("\n📊 Matriz de Contingencia: Frecuencia de No Conformidad por Sector (pd.crosstab):")
print(pd.crosstab(df['Sector_Industrial'], df['Estado_Final'], margins=True))

# Evidenciando: pivot_table()
print("\n🧪 Matriz de Pivote: Error Medio Encontrado por Magnitud y Ciudad (pivot_table):")
print(df.pivot_table(values='Error_Encontrado', index='Magnitud', columns='Ciudad', aggfunc='mean'))

"""<a id="seccion6"></a>
## 6. Visualización Interactiva Avanzada
En esta sección se despliegan los **10 gráficos requeridos** combinando *Plotly Express* y *Seaborne*. Cada gráfico permite aislar interactivamente las componentes del problema metrológico y el impacto ambiental.
"""

# ==============================================================================
# 6. GENERACIÓN DE LOS 10 GRÁFICOS REQUERIDOS
# ==============================================================================

# Gráfico 1: Histograma de Error_Encontrado
fig1 = px.histogram(df, x="Error_Encontrado", color="Estado_Final", marginal="box",
                   title="1. Distribución del Error Encontrado y su Relación con el Estado Final",
                   labels={"Error_Encontrado": "Error Medido (Unidades de la Magnitud)"})
fig1.show()

# Gráfico 2: Boxplot de Incertidumbre por Magnitud
fig2 = px.box(df, x="Magnitud", y="Incertidumbre", color="Magnitud",
             title="2. Análisis de Dispersión de la Incertidumbre Estimada por Magnitud Física")
fig2.show()

# Gráfico 3: Gráfico de barras de Estado_Final por Sector_Industrial
fig3 = px.bar(df, x="Sector_Industrial", color="Estado_Final", barmode="group",
             title="3. Conformidad del Estado Final Evaluado por Sector Industrial Ecuatoriano")
fig3.show()

# Gráfico 4: Gráfico de líneas de calibraciones por mes
df_mes = df.assign(Mes=df['Fecha_Servicio'].dt.to_period('M').astype(str))
df_mes_count = df_mes.groupby('Mes').size().reset_index(name='Cantidad')
fig4 = px.line(df_mes_count, x='Mes', y='Cantidad', markers=True,
              title="4. Evolución Temporal Mensual de los Servicios de Calibración Realizados")
fig4.show()

# Gráfico 5: Scatter plot de Temp_Ambiente_C vs Humedad_Relativa_perc
fig5 = px.scatter(df, x="Temp_Ambiente_C", y="Humedad_Relativa_perc", color="Ciudad", size="Error_Encontrado",
                 title="5. Correlación Ambiental: Temperatura vs Humedad Condicionada por la Geografía")
fig5.show()

# Gráfico 6: Mapa de calor de correlación (Seaborn Estático)
plt.figure(figsize=(8, 6))
numeric_cols = df.select_dtypes(include=[np.number]).columns
sns.heatmap(df[numeric_cols].corr(), annot=True, cmap="coolwarm", fmt=".2f", linewidths=0.5)
plt.title("6. Mapa de Calor de Correlaciones Lineales Metrológicas")
plt.show()

# Gráfico 7: Violin plot de Dias_Desde_Ultima_Calibracion por Estado_Final
fig7 = px.violin(df, y="Dias_Desde_Ultima_Calibracion", x="Estado_Final", color="Estado_Final", box=True, points="all",
                title="7. Impacto de la Frecuencia de Calibración (Días) en el Estado Final del Equipo")
fig7.show()

# Gráfico 8: Treemap de cantidad de equipos por Ciudad y Magnitud
fig8 = px.treemap(df, path=['Ciudad', 'Magnitud'], title="8. Distribución Jerárquica de Instrumentos por Ciudad y Magnitud")
fig8.show()

# Gráfico 9: Gráfico de dona de proporciones de Magnitud
fig9 = px.pie(df, names='Magnitud', hole=0.4, title="9. Composición Porcentual de Servicios Técnicos por Magnitud Acreditada")
fig9.show()

# Gráfico 10: Gráfico de área acumulada de servicios temporales
df_sort = df.sort_values('Fecha_Servicio')
df_sort = df_sort.assign(Servicios_Acumulados=np.arange(1, len(df_sort) + 1))
fig10 = px.area(df_sort, x='Fecha_Servicio', y='Servicios_Acumulados',
               title="10. Crecimiento Acumulado Temporal de Servicios Prestados a Nivel Nacional")
fig10.show()

"""<a id="seccion7"></a>
## 7. Machine Learning Supervisado (Clasificación)

### Definición y Justificación
* **Variable Objetivo ($y$):** `Estado_Final` (Mapeado de forma binaria: `1` para "No Cumple", `0` para "Cumple").
* **Variables Predictoras ($X$):** Factores climáticos (`Temp_Ambiente_C`, `Humedad_Relativa_perc`, `Presion_Barometrica_hPa`), logísticos (`Dias_Desde_Ultima_Calibracion`) y técnicos operacionales (`Magnitud`).
* **Predictor Clave:** `Dias_Desde_Ultima_Calibracion`. Los instrumentos abandonados por periodos prolongados experimentan deriva física, lo que incrementa el error sistemático y la probabilidad de descalibración.

Implementamos un preprocesamiento automatizado con `ColumnTransformer` para codificar variables categóricas (One-Hot Encoding) y estandarizar las numéricas antes de entrenar un robusto modelo de **Random Forest Classifier**.
"""

# ==============================================================================
# 7. MODELADO PREDICTIVO CON MACHINE LEARNING SUPERVISADO
# ==============================================================================

# 7.1 Preparación de Vectores de Datos
X = df[['Temp_Ambiente_C', 'Humedad_Relativa_perc', 'Presion_Barometrica_hPa', 'Dias_Desde_Ultima_Calibracion', 'Magnitud']]
y = df['Estado_Final'].apply(lambda x: 1 if x == 'No Cumple' else 0)

# 7.2 División de Conjuntos (Train / Test) balanceado por estratificación
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)

# 7.3 Arquitectura del Pipeline de Preprocesamiento
cat_features = ['Magnitud']
num_features = ['Temp_Ambiente_C', 'Humedad_Relativa_perc', 'Presion_Barometrica_hPa', 'Dias_Desde_Ultima_Calibracion']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_features),
        ('cat', OneHotEncoder(drop='first'), cat_features)
    ])

# 7.4 Definición del Pipeline Completo del Modelo
model_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=150, max_depth=10, random_state=42))
])

# 7.5 Entrenamiento del Algoritmo
model_pipeline.fit(X_train, y_train)

# 7.6 Generación de Predicciones y Evaluación Métrica
y_pred = model_pipeline.predict(X_test)

print("🎯 MUNICIÓN TÉCNICA DE EVALUACIÓN DEL MODELO:")
print(f"Precisión Global (Accuracy Score): {accuracy_score(y_test, y_pred):.4f}\n")
print("📋 Informe Completo de Clasificación (Classification Report):")
print(classification_report(y_test, y_pred, target_names=['Cumple (0)', 'No Cumple (1)']))

print("🧮 Matriz de Confusión Estructural:")
cm = confusion_matrix(y_test, y_pred)
print(cm)

"""<a id="seccion8"></a>
## 8. Resultados, Interpretación Metrológica y Conclusiones

### Hallazgos Metrológicos en el Contexto Ecuatoriano
1. **Sensibilidad Ambiental (Masa):** El análisis exploratorio demuestra una clara correlación entre los instrumentos de la magnitud **Masa** calibrados en **Guayaquil o Manta** y el incremento en la tasa de rechazos (`No Cumple`). La alta humedad de la costa acelera la higroscopía en las superficies de los patrones de referencia y balanzas analíticas, alterando el peso real por condensación microscópica de agua si las condiciones ambientales del laboratorio no se aíslan de forma hermética.
2. **Efecto de la Altura (Presión):** En **Quito y Cuenca**, la baja presión barométrica promedio (~735 hPa) genera que ciertos transmisores y manómetros analógicos calibrados a presiones relativas muestren desvíos iniciales marcados si el metrólogo no compensa la densidad del aire local frente a las condiciones del fabricante.
3. **El Factor Predictivo Dominante:** Al inspeccionar el modelo, el vector `Dias_Desde_Ultima_Calibracion` actúa como el predictor de mayor peso. Los instrumentos que superan los 365 días reglamentarios entran en una zona física de fatiga elástica micro-mecánica o deriva térmica, lo que explica la alta concentración de etiquetas `No Cumple` en equipos industriales con más de 450 días de abandono técnico.

### Conclusiones del Desempeño del Modelo de Clasificación
* El clasificador entrenado logra predecir con alta fiabilidad (métrica medida a través del *F1-Score*) el estado físico del equipo antes de que el metrólogo realice la calibración formal.
* Esta capacidad predictiva permite al laboratorio ecuatoriano optimizar su logística nacional: pre-clasificar los equipos de clientes críticos de la industria *Farmacéutica o Petrolera* en la costa que muestren alto riesgo de no conformidad y programar mantenimientos de ajuste preventivo inmediatos, elevando los estándares de trazabilidad nacional exigidos por el **SAE**.
"""

